
-- Add sample changelog entries with placeholder images
INSERT INTO changelogs (
  id,
  company_id,
  title,
  content,
  category,
  status,
  visibility,
  featured_image_url,
  tags,
  created_by,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'New Dashboard Analytics',
  '{"blocks":[{"type":"paragraph","data":{"text":"We''ve completely redesigned our analytics dashboard with real-time insights and beautiful visualizations."}}]}',
  'new-feature',
  'published',
  'public',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
  ARRAY['analytics', 'dashboard', 'ui'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Enhanced Security Features',
  '{"blocks":[{"type":"paragraph","data":{"text":"Added two-factor authentication and advanced encryption for better security."}}]}',
  'improvement',
  'published',
  'public',
  'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=400&fit=crop',
  ARRAY['security', '2fa', 'encryption'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '10 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Mobile App Beta Launch',
  '{"blocks":[{"type":"paragraph","data":{"text":"Our mobile app is now available in beta! Download it from the App Store or Google Play."}}]}',
  'new-feature',
  'published',
  'public',
  'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=400&fit=crop',
  ARRAY['mobile', 'app', 'beta'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '15 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'API Rate Limiting Fixed',
  '{"blocks":[{"type":"paragraph","data":{"text":"Fixed issues with API rate limiting that were causing timeouts for some users."}}]}',
  'fix',
  'published',
  'public',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=400&fit=crop',
  ARRAY['api', 'performance', 'bugfix'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '20 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Dark Mode Support',
  '{"blocks":[{"type":"paragraph","data":{"text":"Added system-wide dark mode support with automatic theme switching based on user preferences."}}]}',
  'new-feature',
  'published',
  'public',
  'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=800&h=400&fit=crop',
  ARRAY['ui', 'dark-mode', 'accessibility'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '25 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Performance Improvements',
  '{"blocks":[{"type":"paragraph","data":{"text":"Major performance improvements across the platform with 40% faster loading times."}}]}',
  'improvement',
  'draft',
  'public',
  'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop',
  ARRAY['performance', 'optimization', 'speed'],
  (SELECT id FROM profiles LIMIT 1),
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
);

-- Add sample feedback entries
INSERT INTO feedback_ideas (
  id,
  company_id,
  user_id,
  title,
  description,
  status,
  category,
  tags,
  vote_count,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Add bulk actions for managing items',
  'It would be great to have checkboxes to select multiple items and perform bulk actions like delete, archive, or change status.',
  'under-review',
  'improvement',
  ARRAY['bulk-actions', 'ui', 'productivity'],
  15,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Calendar integration',
  'Integrate with Google Calendar and Outlook to sync events and deadlines.',
  'planned',
  'integration',
  ARRAY['calendar', 'google', 'outlook'],
  23,
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Export data to CSV/Excel',
  'Need ability to export all data to CSV or Excel format for reporting purposes.',
  'completed',
  'feature',
  ARRAY['export', 'csv', 'excel', 'reporting'],
  31,
  NOW() - INTERVAL '14 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Real-time notifications',
  'Push notifications for important updates and mentions would be very helpful.',
  'under-review',
  'feature',
  ARRAY['notifications', 'real-time', 'push'],
  18,
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Advanced search filters',
  'More granular search options with date ranges, tags, and custom fields.',
  'planned',
  'improvement',
  ARRAY['search', 'filters', 'advanced'],
  27,
  NOW() - INTERVAL '9 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Team collaboration features',
  'Comments, mentions, and assignment features for better team collaboration.',
  'under-review',
  'feature',
  ARRAY['collaboration', 'teams', 'comments'],
  12,
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Keyboard shortcuts',
  'Add keyboard shortcuts for common actions to improve productivity.',
  'planned',
  'improvement',
  ARRAY['keyboard', 'shortcuts', 'productivity'],
  22,
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Custom themes and branding',
  'Allow users to customize colors, fonts, and upload their own logos.',
  'under-review',
  'feature',
  ARRAY['themes', 'branding', 'customization'],
  19,
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Offline mode support',
  'Basic offline functionality to view and edit data without internet connection.',
  'under-review',
  'feature',
  ARRAY['offline', 'sync', 'mobile'],
  8,
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Better mobile responsiveness',
  'Some features are hard to use on mobile devices. Need better mobile optimization.',
  'completed',
  'improvement',
  ARRAY['mobile', 'responsive', 'ui'],
  35,
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '7 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'API documentation improvements',
  'API docs need more examples and better organization for developers.',
  'under-review',
  'improvement',
  ARRAY['api', 'documentation', 'developer'],
  14,
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Automated backup system',
  'Automatic daily backups of all user data with easy restore options.',
  'planned',
  'feature',
  ARRAY['backup', 'automation', 'security'],
  26,
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '4 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Video tutorial integration',
  'Embed help videos directly in the app for better user onboarding.',
  'under-review',
  'improvement',
  ARRAY['tutorials', 'video', 'onboarding'],
  11,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Advanced analytics dashboard',
  'More detailed analytics with custom reports and data visualization options.',
  'planned',
  'feature',
  ARRAY['analytics', 'reports', 'visualization'],
  29,
  NOW() - INTERVAL '11 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  (SELECT id FROM profiles LIMIT 1),
  'Single sign-on (SSO) support',
  'Support for SAML and OAuth SSO providers for enterprise customers.',
  'under-review',
  'feature',
  ARRAY['sso', 'authentication', 'enterprise'],
  17,
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '3 days'
);

-- Add some sample inbox messages
INSERT INTO inbox_messages (
  id,
  user_id,
  company_id,
  from_email,
  from_name,
  subject,
  content,
  html_content,
  category,
  enhanced_category,
  ai_summary,
  ai_tags,
  confidence_score,
  processed_by_ai,
  is_processed,
  received_at,
  created_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM companies LIMIT 1),
  'updates@stripe.com',
  'Stripe',
  'New payment methods now available',
  'We''ve added support for new payment methods including Apple Pay and Google Pay.',
  '<p>We''ve added support for new payment methods including Apple Pay and Google Pay.</p>',
  'product-update',
  'payment-integration',
  'Stripe has announced support for Apple Pay and Google Pay payment methods.',
  ARRAY['payments', 'apple-pay', 'google-pay'],
  0.95,
  true,
  true,
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM companies LIMIT 1),
  'noreply@github.com',
  'GitHub',
  'Security alert: New login detected',
  'A new login to your GitHub account was detected from a new device.',
  '<p>A new login to your GitHub account was detected from a new device.</p>',
  'security',
  'security-alert',
  'GitHub security notification about a new login from an unrecognized device.',
  ARRAY['security', 'login', 'alert'],
  0.88,
  true,
  true,
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM companies LIMIT 1),
  'team@figma.com',
  'Figma',
  'New collaboration features in Figma',
  'Introducing real-time cursors and improved commenting system for better team collaboration.',
  '<p>Introducing real-time cursors and improved commenting system for better team collaboration.</p>',
  'product-update',
  'collaboration-tools',
  'Figma has released new collaboration features including real-time cursors and enhanced commenting.',
  ARRAY['figma', 'collaboration', 'design'],
  0.92,
  true,
  true,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM companies LIMIT 1),
  'hello@linear.app',
  'Linear',
  'Linear Insights: Your team''s productivity report',
  'Here''s your weekly productivity report with key metrics and insights.',
  '<p>Here''s your weekly productivity report with key metrics and insights.</p>',
  'analytics',
  'productivity-report',
  'Weekly productivity report from Linear with team metrics and performance insights.',
  ARRAY['linear', 'productivity', 'analytics'],
  0.85,
  true,
  true,
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM companies LIMIT 1),
  'support@notion.so',
  'Notion',
  'Notion AI is now available',
  'Notion AI is now available to help you write, brainstorm, and organize your thoughts.',
  '<p>Notion AI is now available to help you write, brainstorm, and organize your thoughts.</p>',
  'product-update',
  'ai-features',
  'Notion has launched AI features to assist with writing, brainstorming, and content organization.',
  ARRAY['notion', 'ai', 'writing'],
  0.90,
  true,
  true,
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '4 days'
);
